version: 1
disable_existing_loggers: true
formatters:
  brief: 
    format: '%(asctime)s | %(filename)s > %(funcName)s() | %(message)s'
  precise: 
    format: '%(asctime)s 〔 %(filename)s > %(funcName)s() > %(lineno)s 〕: %(message)s'
handlers:
  console:
    class : logging.StreamHandler
    level   : DEBUG
    formatter: brief
    # filters: [allow_foo]
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: error.log
    maxBytes: 1024
    backupCount: 3  
loggers:
  info:
    level: INFO
    handlers: [console]
    propogate: no
  error:
    level: ERROR
    handlers: [file]
    propogate: no
